version: '2'
services:
    mysql:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=temp123
            - MYSQL_DATABASE=tcar_master
        ports:
            - 3309:3306
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./trc/mysql:/docker-entrypoint-initdb.d
        networks:
            - back

    php:
        build: ./trc
        environment:
            - MYSQL_ROOT_PASSWORD=temp123
            - MYSQL_DATABASE=tcar_master
            - ADMIN_IP=192.168.2.103
            - BACKEND_IP=192.168.2.103
        ports:
            - 8088:80
        volumes:
            - ./trc/upload/api:/var/www/html/api
            - ./trc/upload/admin:/var/www/html/admin
        links:
            - mysql
        networks:
            - back

    composer:
        image: composer/composer
        working_dir: /var/www/html/api/v1
        command: install
        volumes:
            - ./trc/upload/api/v1:/var/www/html/api/v1
        links:
            - php
        networks:
            - back

networks:
  back:
    driver: bridge
